name: Playwright Tests for Config Specs
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  config:
    uses: ./.github/workflows/playwright-test-group.yml
    with:
      test_path: specs/config
      artifact_name: config
      group_name: Config
    secrets:
      APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_API_KEY }}
