name: Studio - Proxy Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  proxy:
    uses: ./.github/workflows/playwright-test-group.yml
    with:
      test_path: specs/proxy
      artifact_name: proxy
      group_name: Proxy
    secrets:
      APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_API_KEY }}
      SPECMATIC_LICENSE_KEY: ${{ secrets.SPECMATIC_LICENSE_KEY }}
